version: 2.1

orbs:
  tools: gotest/tools@0.0.10

jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: ~/repo

    steps:
      - checkout
      - run: make test

  runlinter:
    executor: circleci-golang
    steps:
      - checkout
      - mod-download
      - install-golangci-lint:
          version: 1.15.0
      - run:
          name: Lint
          command: |
            golangci-lint run -v \
              --concurrency 2


workflows:
  build_deploy:
    jobs:
      - build
      - runlinter