version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: ~/repo

    steps:
      - checkout
      - run: make test

workflows:
  build_deploy:
    jobs:
      - build