version: 2.1

orbs:
  tools: gotest/tools@0.0.10

jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: ~/repo

    steps:
      - checkout
      - run: make test
  lintergo:
    executor: circleci-golang

workflows:
  build_deploy:
    jobs:
      - build
      - lintergo